import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {Poppins} from "next/font/google"
import ResponsiveNav from "@/components/navbar/ResponsiveNav";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import ScrollToTop from "@/components/helper/ScrollToTop";

const font = Poppins({
  weight:["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets:["latin"]
})

/*
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
*/
/*
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
*/
/*
export const metadata: Metadata = {
  title: "Travel for You | Next js 15",
  description: "Generated by Frank Designs",
};
*/
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${font.className} antialiased`}>
          <ResponsiveNav/>
        {children}
        <Footer/>
        <ScrollToTop/>
      </body>
    </html>
  );
}
